### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by webbrowser11**
fix

### CODE REVIEW

**Comment by G1aD05** [comment]
Author data can't contain two usernames/emails

**Comment by webbrowser11** [comment]
then how are we gonna classify me as an author now?

**Comment by webbrowser11** [comment]
oh i see.... i was getting confused with pyproject.toml

**Comment by G1aD05** [comment]
I'll use the .toml file instead

**Comment by webbrowser11** [comment]
just wanna make sure, can i release to PyPI now?

**Comment by G1aD05** [comment]
I already released it

**Comment by webbrowser11** [comment]
i know but if i want to can i release one?

**Comment by G1aD05** [comment]
Sure, but do I need to edit any perms?

**Comment by webbrowser11** [comment]
idk let em try to release a test one. just change the readme or smth

**Comment by G1aD05** [comment]
I can add you as a collaborator in settings but I'm not if that's how it works

**Comment by webbrowser11** [comment]
ur talking about github not [PyPI](pypi.org/project/scratchcon)

**Comment by webbrowser11** [comment]
just make a release called test or smth now

**Comment by G1aD05** [comment]
https://github.com/G1aD05/scratchcon/releases/tag/Test

**Comment by webbrowser11** [comment]
NO NOT YET!!!!!!

**Comment by G1aD05** [comment]
Oh

**Comment by webbrowser11** [comment]
i was just thinking we had to actually update something. so if u made it u can delete it imma make a pr then you can release it.

**Comment by G1aD05** [comment]
I'll add you as a collaborator on PyPI for scratchcon

**Comment by G1aD05** [comment]
Done

**Comment by webbrowser11** [comment]
there is nothing for that i think

**Comment by G1aD05** [comment]
Well, I found a collaborator setting in the project settings

**Comment by webbrowser11** [comment]
ok do that

**Comment by webbrowser11** [comment]
my pypi:
https://pypi.org/user/webbrowser11/

just use my username

**Pull request closed without merging**
