### PR TITLE
clean up requirments.txt

### PR DESCRIPTION
**Pull request by webbrowser11**
if you need an explanation why i did this its because `pip freeze > requirements.txt` gets all the installed python packages on the system not just a project yes, i forgot to give giados the more direct requirements generator, so it was extra work, sue me (dont actually im not even 18).

### CODE REVIEW

**Comment by webbrowser11** [comment]
BTW, is Washington as breezy as Portland Oregon rn?

**Comment by webbrowser11** [comment]
cause it hella breezy for like another hour or smth

**Comment by G1aD05** [comment]
It's not windy at all

**Comment by G1aD05** [comment]
It's just cold

**Comment by webbrowser11** [comment]
oh,

**Comment by webbrowser11** [comment]
wait what?
Screenshot 2024-11-07 194501

**Comment by webbrowser11** [comment]
it said 5mph last morning but it seemed like 20...

**Comment by G1aD05** [comment]
Well, it's not very windy in my location

**Comment by webbrowser11** [comment]
lucky you...

**Comment by webbrowser11** [comment]
bye

**Comment by G1aD05** [comment]
It's only 2 MPH

**Comment by G1aD05** [comment]
bye

**Pull request merged**
