### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by webbrowser11**
update
just make this release have a normal name and tag. ONLY RELEASE IT TO GITHUB!!! ill to release it to PyPI.

### CODE REVIEW

**Comment by webbrowser11** [comment]
also u should add me as contrib on github.

**Comment by G1aD05** [comment]
alr I'll create the release

**Comment by G1aD05** [comment]
I'm so confused...

**Comment by webbrowser11** [comment]
just lemme do my thing

**Comment by webbrowser11** [comment]
ight add me as PyPI collaborator.

**Comment by G1aD05** [comment]
You haven't accepted the invite I sent, maybe check your email, also I already made a release on PyPI called 1.3.1-beta

**Comment by webbrowser11** [comment]
oh.... can you delete that? the whole point of it was to see if **I** could update it

**Comment by G1aD05** [comment]
Uh well 1.3.1-beta contains your contribution info

**Comment by G1aD05** [comment]
You can release 1.3.2-beta though

**Comment by webbrowser11** [comment]
oh dam i messed up hang on

**Comment by webbrowser11** [comment]
ight there was one typo you can release the one with that fixed whenever bye bye imma go do other stuff

**Comment by G1aD05** [comment]
alr

**Comment by webbrowser11** [comment]
kkkkk

**Pull request merged**
